#!/usr/bin/env python3
import pandas as pd
import matplotlib.pyplot as plt

def main():
    # Read the errors CSV generated by the C++ solver
    df = pd.read_csv('zgesv_error.csv')

    # Create plot
    plt.figure(figsize=(8,6))
    plt.plot(df['n'], df['l2norm_residual'], marker='o', label='l2norm_residual')
    plt.plot(df['n'], df['normalized_error'], marker='s', label='normalized_error')

    # Logarithmic x-axis (base 2) since n doubles each time
    plt.xscale('log', base=2)
    plt.yscale('log')  # Logarithmic y-axis
    plt.xlabel('Matrix dimension n')
    plt.ylabel('log(error)')
    plt.title('Log of Residual & Normalized Error of LAPACKE_zgesv vs N')
    plt.grid(which='both', linestyle='--', alpha=0.5)
    plt.legend()
    plt.tight_layout()

    # Save and show
    plt.savefig('zgesv_error_plot.png', dpi=300)
    plt.show()

if __name__ == '__main__':
    main()
